[package]
name = "gitplay-rust"
version = "0.1.0"
authors = ["Sumit Datta <sumitdatta@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"

[dependencies]
iced = "0.3.0"
git2 = "0.13.20"
smart-default = "0.6.0"